export interface Article {
  title: string;
  slug: string;
  description: string;
  type: "pillar" | "cluster";
}

export interface Category {
  slug: string;
  title: string;
  emoji: string;
  description: string;
  metaTitle: string;
  metaDescription: string;
  pillars: Article[];
  clusters: Article[];
}

export const categories: Category[] = [
  {
    slug: "starta-foretag",
    title: "Starta Företag",
    emoji: "🚀",
    description: "Allt du behöver veta för att starta och registrera ditt företag i Sverige.",
    metaTitle: "Starta Företag – Guide för nya företagare | Driva Företag",
    metaDescription: "Komplett guide för att starta företag i Sverige. Bolagsformer, registrering, affärsplan och allt du behöver veta som ny företagare.",
    pillars: [
      { title: "Enskild firma vs Aktiebolag – Vilken bolagsform passar dig?", slug: "enskild-firma-vs-aktiebolag", description: "Jämför enskild firma och aktiebolag. Fördelar, nackdelar, skatt och ansvar.", type: "pillar" },
      { title: "Affärsplan – gratis mall och guide", slug: "affarsplan-mall", description: "Steg-för-steg-guide till en affärsplan som imponerar på banker och investerare.", type: "pillar" },
      { title: "Registrera företag hos Bolagsverket", slug: "registrera-foretag", description: "Allt om F-skatt, moms, Bolagsverket och bankkonto för nya företag.", type: "pillar" },
    ],
    clusters: [
      { title: "Starta enskild firma – komplett guide", slug: "starta-enskild-firma", description: "Registrera enskild firma snabbt och enkelt.", type: "cluster" },
      { title: "Starta aktiebolag – steg-för-steg", slug: "starta-aktiebolag", description: "Komplett guide till att starta AB.", type: "cluster" },
      { title: "Starta eget utan pengar", slug: "starta-utan-pengar", description: "Så startar du företag med minimal budget.", type: "cluster" },
      { title: "Företagsnamn – regler och tips", slug: "foretagsnamn", description: "Välj rätt namn för ditt företag.", type: "cluster" },
      { title: "Aktiekapital – hur mycket behöver du?", slug: "aktiekapital", description: "Allt om krav på aktiekapital.", type: "cluster" },
      { title: "Starta företag vid sidan av anställning", slug: "starta-eget-med-anstallning", description: "Kombinera anställning och eget företag.", type: "cluster" },
      { title: "50+ affärsidéer att starta", slug: "affarside", description: "Metoder för att hitta och validera din affärsidé.", type: "cluster" },
      { title: "Bästa företagskontot – jämförelse", slug: "foretagskonto", description: "Jämför företagskonton hos svenska banker.", type: "cluster" },
      { title: "Starta företag checklista", slug: "checklista", description: "Komplett checklista för nya företagare.", type: "cluster" },
      { title: "Starta konsultbolag – guide", slug: "starta-konsultbolag", description: "Komplett guide för konsulter.", type: "cluster" },
      { title: "Starta e-handel i Sverige", slug: "starta-ehandel", description: "Guide till e-handel och nätbutik.", type: "cluster" },
      { title: "Starta handelsbolag – guide", slug: "starta-handelsbolag", description: "Allt om handelsbolag som företagsform.", type: "cluster" },
      { title: "Hobby eller företag – var går gränsen?", slug: "hobbyverksamhet-vs-foretag", description: "Skatteverkets krav och regler förklarade.", type: "cluster" },
      { title: "Företagsförsäkring – vilken behöver du?", slug: "foretagsforsakring", description: "Rätt försäkringar för ditt företag.", type: "cluster" },
      { title: "Starta restaurang – tillstånd och regler", slug: "starta-restaurang", description: "Serveringstillstånd, budget och personal.", type: "cluster" },
      { title: "Byta bolagsform – enskild firma till AB", slug: "byta-bolagsform", description: "Så byter du från enskild firma till aktiebolag.", type: "cluster" },
      { title: "Starta företag utomlands som svensk", slug: "starta-foretag-utomlands", description: "Guide för svenskar som vill starta utomlands.", type: "cluster" },
      { title: "Ekonomisk förening – guide och regler", slug: "ekonomisk-forening", description: "Allt om ekonomiska föreningar.", type: "cluster" },
      { title: "Starta företag som student", slug: "starta-foretag-som-student", description: "CSN-regler och tips för studenter.", type: "cluster" },
      { title: "Franchise i Sverige – guide", slug: "franchise-guide", description: "Så kommer du igång med franchise.", type: "cluster" },
      { title: "Företagsnamn – särskiljningsförmåga", slug: "sarboskillnad", description: "Bolagsverkets krav på unika namn.", type: "cluster" },
      { title: "SWOT-analys – mall och guide", slug: "swot-analys", description: "Strategisk planering med SWOT.", type: "cluster" },
    ],
  },
  {
    slug: "bokforing-ekonomi",
    title: "Bokföring & Ekonomi",
    emoji: "📊",
    description: "Lär dig bokföring, ekonomistyrning och hur du håller koll på företagets pengar.",
    metaTitle: "Bokföring & Ekonomi – Guide för företagare | Driva Företag",
    metaDescription: "Lär dig bokföring, ekonomistyrning och kassaflöde. Praktiska tips för att hålla koll på företagets ekonomi.",
    pillars: [
      { title: "Bokföring för enskild firma – komplett guide", slug: "bokforing-enskild-firma", description: "Grunderna i bokföring för enskild firma.", type: "pillar" },
      { title: "Bästa bokföringsprogrammet – jämförelse", slug: "basta-bokforingsprogram", description: "Test och jämförelse av populära bokföringsprogram.", type: "pillar" },
      { title: "Bokföring för aktiebolag – steg-för-steg", slug: "bokforing-aktiebolag", description: "Komplett guide till bokföring i AB.", type: "pillar" },
    ],
    clusters: [
      { title: "Årsredovisning – komplett guide för AB", slug: "arsredovisning-guide", description: "Komplett guide till årsredovisning.", type: "cluster" },
      { title: "BAS-kontoplanen förklarad", slug: "bas-kontoplanen", description: "Guide till BAS-kontoplanen.", type: "cluster" },
      { title: "Fakturamall – gratis mall och lagkrav", slug: "faktura-mall", description: "Regler och tips för fakturering.", type: "cluster" },
      { title: "Förenklat årsbokslut – guide", slug: "forenklat-arsbokslut", description: "K1-regelverket och förenklat bokslut.", type: "cluster" },
      { title: "Avskrivningar – regler och metoder", slug: "avskrivningar", description: "Regler för avskrivningar.", type: "cluster" },
      { title: "Kassaflödesprognos – mall och guide", slug: "kassaflodesprognos", description: "Förstå och förbättra kassaflödet.", type: "cluster" },
      { title: "Verifikationer i bokföring", slug: "verifikation-bokforing", description: "Hantera verifikationer korrekt.", type: "cluster" },
      { title: "Inventering – regler och tips", slug: "inventering-guide", description: "Praktisk guide till inventering.", type: "cluster" },
      { title: "Resultatrapport – så läser du den", slug: "resultatrapport", description: "Förstå resultaträkningen.", type: "cluster" },
      { title: "Balansrapport förklarad", slug: "balansrapport", description: "Tillgångar, skulder och eget kapital.", type: "cluster" },
      { title: "Periodiseringsfond – regler och bokföring", slug: "periodiseringsfond", description: "Skjut upp skatten lagligt.", type: "cluster" },
      { title: "Representation – avdragsregler", slug: "representation-avdrag", description: "Regler för representation.", type: "cluster" },
      { title: "Likviditetsbudget – mall och tips", slug: "likviditetsbudget", description: "Skapa en budget som fungerar.", type: "cluster" },
      { title: "Egen insättning och eget uttag", slug: "egen-insattning-eget-uttag", description: "Bokföring av egna uttag.", type: "cluster" },
      { title: "Fakturerings- vs kontantmetoden", slug: "faktureringsmetoden-vs-kontantmetoden", description: "Välj rätt momsmetod.", type: "cluster" },
      { title: "SIE-filer – vad är det?", slug: "sie-filer", description: "Exportera bokföringsdata.", type: "cluster" },
      { title: "Fortnox recension", slug: "fortnox-recension", description: "Djupgående recension av Fortnox.", type: "cluster" },
      { title: "Bokio recension", slug: "bokio-recension", description: "Recension av Bokio bokföring.", type: "cluster" },
      { title: "Visma eEkonomi recension", slug: "visma-eaccounting-recension", description: "Recension av Visma eEkonomi.", type: "cluster" },
    ],
  },
  {
    slug: "juridik",
    title: "Juridik",
    emoji: "⚖️",
    description: "Avtal, lagar och juridiska frågor för svenska företagare.",
    metaTitle: "Juridik för företag – Avtal, lagar och regler | Driva Företag",
    metaDescription: "Juridik för företagare. Avtal, GDPR, arbetsrätt och viktiga lagar du behöver känna till.",
    pillars: [
      { title: "Avtal för företagare – komplett guide", slug: "avtal-guide", description: "Allt om avtal och juridik för företag.", type: "pillar" },
      { title: "GDPR för företag – vad du måste göra", slug: "gdpr-foretag", description: "Praktisk GDPR-guide för företag.", type: "pillar" },
      { title: "Arbetsrätt – grunderna för arbetsgivare", slug: "arbetsratt", description: "Arbetsrättsliga regler för företagare.", type: "pillar" },
    ],
    clusters: [
      { title: "Aktieägaravtal – mall och guide", slug: "aktieavtal", description: "Så skriver du aktieägaravtal.", type: "cluster" },
      { title: "Kundavtal och allmänna villkor", slug: "kundavtal", description: "Skapa tydliga kundavtal.", type: "cluster" },
      { title: "Konsultavtal – mall och tips", slug: "konsultavtal", description: "Guide till konsultavtal.", type: "cluster" },
      { title: "Varumärkesskydd – registrera och skydda", slug: "varumarkesskydd", description: "Skydda ditt varumärke och namn.", type: "cluster" },
      { title: "Tvistelösning – domstol eller skiljedom?", slug: "tvistlosning", description: "Hantera konflikter och tvister.", type: "cluster" },
      { title: "Sekretessavtal (NDA)", slug: "sekretessavtal", description: "Mall och guide för NDA.", type: "cluster" },
      { title: "Personuppgiftsbiträdesavtal (PUB-avtal)", slug: "pub-avtal", description: "GDPR-krav för leverantörer.", type: "cluster" },
      { title: "Anställningsavtal – mall och regler", slug: "anstallningsavtal", description: "Skapa korrekta anställningsavtal.", type: "cluster" },
      { title: "Bolagsordning – vad ska stå med?", slug: "bolagsordning", description: "Så skriver du bolagsordning.", type: "cluster" },
      { title: "Styrelseansvar i aktiebolag", slug: "styrelseansvar", description: "Personligt ansvar i styrelsen.", type: "cluster" },
      { title: "Avveckla aktiebolag – steg-för-steg", slug: "avveckla-aktiebolag", description: "Likvidation och avveckling.", type: "cluster" },
      { title: "Upphovsrätt för företag", slug: "upphovsratt-foretag", description: "Skydda ditt innehåll.", type: "cluster" },
      { title: "Konkurrensklausul – regler och giltighet", slug: "konkurrensklausul", description: "Regler för konkurrensklausuler.", type: "cluster" },
      { title: "Inkasso – driv in obetalda fakturor", slug: "inkasso-guide", description: "Process och kostnader.", type: "cluster" },
      { title: "Offentlig upphandling – guide", slug: "offentlig-upphandling", description: "Vinn offentliga anbud.", type: "cluster" },
      { title: "Dataskyddsombud (DPO)", slug: "dataskyddsombud", description: "Behöver ditt företag ett DPO?", type: "cluster" },
      { title: "Ägarbyte i aktiebolag", slug: "agarbyte-aktiebolag", description: "Köpa och sälja aktier.", type: "cluster" },
    ],
  },
  {
    slug: "marknadsforing",
    title: "Marknadsföring",
    emoji: "📣",
    description: "Strategier för digital marknadsföring, SEO och sociala medier.",
    metaTitle: "Marknadsföring för företag – SEO, SoMe & strategi | Driva Företag",
    metaDescription: "Digital marknadsföring för företagare. SEO, sociala medier, content marketing och strategier som fungerar.",
    pillars: [
      { title: "SEO för företag – komplett guide", slug: "seo-guide", description: "Lär dig SEO från grunden.", type: "pillar" },
      { title: "Content marketing-strategi som fungerar", slug: "content-marketing", description: "Skapa innehåll som ger resultat.", type: "pillar" },
      { title: "Varumärkesbyggande – skapa ett starkt varumärke", slug: "varumarkesbyggande", description: "Bygg ett starkt varumärke.", type: "pillar" },
    ],
    clusters: [
      { title: "Google Ads för nybörjare", slug: "google-ads-guide", description: "Starta med Google Ads.", type: "cluster" },
      { title: "E-postmarknadsföring – verktyg och tips", slug: "epost-marknadsforing", description: "Nyhetsbrev och e-postflöden.", type: "cluster" },
      { title: "Instagram för företag", slug: "instagram-foretag", description: "Marknadsför dig på Instagram.", type: "cluster" },
      { title: "LinkedIn-marknadsföring", slug: "linkedin-marknadsforing", description: "B2B-marknadsföring på LinkedIn.", type: "cluster" },
      { title: "Google Business Profile – lokal SEO", slug: "google-business-profile", description: "Lokal synlighet på Google.", type: "cluster" },
      { title: "Copywriting – skriv texter som säljer", slug: "copywriting-guide", description: "Skriv texter som konverterar.", type: "cluster" },
      { title: "Videomarknadsföring – YouTube och Reels", slug: "videomarknadsforing", description: "Använd video i marknadsföringen.", type: "cluster" },
      { title: "Remarketing och retargeting", slug: "remarketing-retargeting", description: "Nå tillbaka besökare.", type: "cluster" },
      { title: "TikTok för företag", slug: "tiktok-foretag", description: "Marknadsföring på TikTok.", type: "cluster" },
      { title: "Konverteringsoptimering (CRO)", slug: "konverteringsoptimering", description: "Öka konverteringsgraden.", type: "cluster" },
      { title: "Facebook-annonsering – guide", slug: "facebook-annonsering", description: "Meta Ads för företag.", type: "cluster" },
      { title: "Nyhetsbrev – bygg en e-postlista", slug: "nyhetsbrev-guide", description: "Bygg och väx din e-postlista.", type: "cluster" },
      { title: "Influencer marketing för företag", slug: "influencer-marketing", description: "Samarbeta med influencers.", type: "cluster" },
      { title: "Podcast som marknadsföring", slug: "podcast-marknadsforing", description: "Starta en företagspodcast.", type: "cluster" },
      { title: "Affiliate marketing för företag", slug: "affiliate-marketing", description: "Starta ett affiliateprogram.", type: "cluster" },
      { title: "PR och pressmeddelanden", slug: "pr-pressmeddelanden", description: "Få publicitet för småföretag.", type: "cluster" },
      { title: "Lokal marknadsföring", slug: "lokal-marknadsforing", description: "Nå kunder i ditt område.", type: "cluster" },
      { title: "Kundrecensioner – strategi", slug: "kundrecensioner-strategi", description: "Få fler och bättre omdömen.", type: "cluster" },
    ],
  },
  {
    slug: "finansiering",
    title: "Finansiering",
    emoji: "💰",
    description: "Hitta rätt finansiering för ditt företag – lån, bidrag och investeringar.",
    metaTitle: "Finansiering för företag – Lån, bidrag & investerare | Driva Företag",
    metaDescription: "Hitta rätt finansiering. Företagslån, bidrag, riskkapital och crowdfunding för svenska företag.",
    pillars: [
      { title: "Företagslån – jämför och ansök", slug: "foretagslan", description: "Guide till företagslån i Sverige.", type: "pillar" },
      { title: "Bidrag och stöd för företagare", slug: "bidrag-stod", description: "Alla bidrag och stöd du kan söka.", type: "pillar" },
      { title: "Riskkapital – så pitchar du till VC", slug: "riskkapital-guide", description: "Hitta investerare till ditt företag.", type: "pillar" },
    ],
    clusters: [
      { title: "Almi-lån – krav och ansökan", slug: "almi-lan", description: "Almis lånetyper och rådgivning.", type: "cluster" },
      { title: "Crowdfunding i Sverige", slug: "crowdfunding", description: "Finansiera via crowdfunding.", type: "cluster" },
      { title: "Factoring – frigör kapital", slug: "factoring", description: "Frigör kapital från fakturor.", type: "cluster" },
      { title: "Starta eget-bidrag", slug: "starta-eget-bidrag", description: "Bidrag från Arbetsförmedlingen.", type: "cluster" },
      { title: "Leasing av utrustning", slug: "leasing", description: "Leasa utrustning och fordon.", type: "cluster" },
      { title: "Bootstrap – väx utan extern finansiering", slug: "bootstrap", description: "Finansiera tillväxt med eget kassaflöde.", type: "cluster" },
      { title: "EU-bidrag för svenska företag", slug: "eu-bidrag-foretag", description: "EU-finansiering och stöd.", type: "cluster" },
      { title: "Företagskredit vs företagslån", slug: "foretagskredit-vs-foretagslan", description: "Skillnaden mellan kredit och lån.", type: "cluster" },
      { title: "Mikrolån för företagare", slug: "mikrolan", description: "Små lån för småföretag.", type: "cluster" },
      { title: "Pitch deck – övertyga investerare", slug: "pitch-deck", description: "Skapa en vinnande presentation.", type: "cluster" },
      { title: "Vinnova-bidrag – ansökan och krav", slug: "vinnova-bidrag", description: "Bidrag för innovativa företag.", type: "cluster" },
      { title: "Tillväxtverkets stöd", slug: "tillvaxtverket-stod", description: "Affärsutvecklingscheckar och program.", type: "cluster" },
      { title: "Företagsobligation – finansiering", slug: "foretagsobligation", description: "Obligationer för växande bolag.", type: "cluster" },
    ],
  },
  {
    slug: "skatt",
    title: "Skatt",
    emoji: "🧾",
    description: "Skatteregler, deklaration och optimering för företagare.",
    metaTitle: "Skatt för företag – Deklaration, regler & tips | Driva Företag",
    metaDescription: "Förstå skatteregler för företag. Moms, arbetsgivaravgifter, deklaration och skatteoptimering.",
    pillars: [
      { title: "Skatteplanering aktiebolag – laglig optimering", slug: "skatteplanering-aktiebolag", description: "Alla skattestrategier för AB-ägare.", type: "pillar" },
      { title: "F-skatt – komplett guide", slug: "f-skatt", description: "Allt om F-skatt och FA-skatt.", type: "pillar" },
      { title: "Moms för företag – komplett guide", slug: "momsguide", description: "Momsregler, satser och deklaration.", type: "pillar" },
    ],
    clusters: [
      { title: "Arbetsgivaravgifter – beräkning och regler", slug: "arbetsgivaravgifter", description: "Så beräknas arbetsgivaravgifter.", type: "cluster" },
      { title: "3:12-reglerna förklarade", slug: "3-12-reglerna", description: "Fåmansbolagsreglerna.", type: "cluster" },
      { title: "ROT- och RUT-avdrag – regler", slug: "rot-rut-avdrag", description: "Regler för ROT och RUT.", type: "cluster" },
      { title: "Skattekonto – så fungerar det", slug: "skattekonto", description: "Hantera ditt skattekonto.", type: "cluster" },
      { title: "Preliminärskatt – beräkna och betala", slug: "preliminarskatt", description: "Beräkna och betala preliminär skatt.", type: "cluster" },
      { title: "Deklarera enskild firma – NE-bilagan", slug: "deklarera-enskild-firma", description: "Steg-för-steg genom NE-bilagan.", type: "cluster" },
      { title: "Egenavgifter i enskild firma", slug: "egenavgifter", description: "Beräkning och regler för egenavgifter.", type: "cluster" },
      { title: "Utdelning i fåmansföretag", slug: "utdelning-famansforetag", description: "Optimera lön och utdelning.", type: "cluster" },
      { title: "Tjänstebil eller milersättning?", slug: "tjanstebil-vs-milersattning", description: "Förmånsbeskattning av bil.", type: "cluster" },
      { title: "Moms vid handel inom EU", slug: "moms-eu-handel", description: "EU-moms och omvänd skattskyldighet.", type: "cluster" },
      { title: "Omvänd skattskyldighet – guide", slug: "omvand-skattskyldighet", description: "Regler för bygg och utland.", type: "cluster" },
      { title: "Skatteavdrag för företagare", slug: "skatteavdrag-foretag", description: "Alla avdragsgilla kostnader.", type: "cluster" },
      { title: "Pension som företagare", slug: "pension-foretagare", description: "Bygg din pension rätt.", type: "cluster" },
      { title: "Reseavdrag för företagare", slug: "reseavdrag-foretag", description: "Traktamente och bilersättning.", type: "cluster" },
      { title: "Hemmakontor – avdrag och regler", slug: "hemmakontor-avdrag", description: "Avdrag för hemmakontoret.", type: "cluster" },
      { title: "Kryptoskatt i Sverige", slug: "kryptoskatt", description: "Så beskattas kryptovalutor.", type: "cluster" },
      { title: "Internationell moms – export/import", slug: "internationell-moms", description: "Moms vid handel utanför EU.", type: "cluster" },
    ],
  },
  {
    slug: "personal-hr",
    title: "Personal & HR",
    emoji: "👥",
    description: "Rekrytering, arbetsgivaransvar och att bygga ett framgångsrikt team.",
    metaTitle: "Personal & HR – Anställ, led och utveckla | Driva Företag",
    metaDescription: "Guide till personalfrågor för företagare. Rekrytering, anställningsavtal, löner och arbetsgivaransvar.",
    pillars: [
      { title: "Anställa personal – komplett guide", slug: "anstalla-personal", description: "Allt om att anställa din första medarbetare.", type: "pillar" },
      { title: "Lönehantering för småföretag", slug: "lonehantering", description: "Praktisk guide till löner.", type: "pillar" },
      { title: "Rekrytering – hitta rätt personal", slug: "rekrytering-guide", description: "Komplett rekryteringsguide.", type: "pillar" },
    ],
    clusters: [
      { title: "Semesterlagen – regler och beräkning", slug: "semesterlagen", description: "Regler för semester.", type: "cluster" },
      { title: "Kollektivavtal – behöver du ett?", slug: "kollektivavtal", description: "Guide till kollektivavtal.", type: "cluster" },
      { title: "Uppsägning – regler och process", slug: "uppsagning", description: "Så hanterar du uppsägning.", type: "cluster" },
      { title: "Friskvårdsbidrag – regler", slug: "friskvardsbidrag", description: "Förmåner för anställda.", type: "cluster" },
      { title: "Distansarbete – policy och regler", slug: "distansarbete-policy", description: "Policys för distansarbete.", type: "cluster" },
      { title: "Tjänstepension – så väljer du rätt", slug: "tjanstepension", description: "ITP, SAF-LO och pensionsval.", type: "cluster" },
      { title: "Arbetsmiljö – ditt ansvar", slug: "arbetsmiljo", description: "Systematiskt arbetsmiljöarbete.", type: "cluster" },
      { title: "Lönerevision – guide för arbetsgivare", slug: "lonerevision", description: "Årlig löneöversyn.", type: "cluster" },
      { title: "Medarbetarsamtal – mall och tips", slug: "medarbetarsamtal", description: "Effektiva utvecklingssamtal.", type: "cluster" },
      { title: "Personalhandbok – mall och innehåll", slug: "personalhandbok-mall", description: "Skapa tydliga riktlinjer.", type: "cluster" },
      { title: "Onboarding – checklista", slug: "onboarding-guide", description: "Introduktion av nya medarbetare.", type: "cluster" },
    ],
  },
  {
    slug: "ai-effektivisering",
    title: "AI & Effektivisering",
    emoji: "🤖",
    description: "Använd AI och digitala verktyg för att effektivisera ditt företag.",
    metaTitle: "AI & Effektivisering – Smartare företagande | Driva Företag",
    metaDescription: "Effektivisera företaget med AI och digitala verktyg. Praktiska tips för automatisering och produktivitet.",
    pillars: [
      { title: "AI för företagare – komplett guide", slug: "ai-guide-foretagare", description: "Praktisk guide till AI för företagare.", type: "pillar" },
      { title: "Automatisera ditt företag – steg-för-steg", slug: "automatisera-foretag", description: "Automatisera rutinuppgifter.", type: "pillar" },
      { title: "Bästa AI-verktygen för småföretag", slug: "basta-ai-verktyg", description: "Bästa verktygen för varje behov.", type: "pillar" },
    ],
    clusters: [
      { title: "ChatGPT för företag – praktiska tips", slug: "chatgpt-foretag", description: "Använd ChatGPT i ditt företag.", type: "cluster" },
      { title: "AI-driven marknadsföring", slug: "ai-marknadsforing", description: "AI i marknadsföring.", type: "cluster" },
      { title: "AI-bokföring – framtiden är här", slug: "ai-bokforing", description: "AI för ekonomihantering.", type: "cluster" },
      { title: "AI för kundtjänst – chatbotar", slug: "ai-kundtjanst", description: "Automatisera kundservice.", type: "cluster" },
      { title: "Zapier och Make – automatisera utan kod", slug: "zapier-make-guide", description: "Koppla ihop dina verktyg.", type: "cluster" },
      { title: "No-code-verktyg för företagare", slug: "no-code-verktyg", description: "Bygg utan programmering.", type: "cluster" },
      { title: "Produktivitetsverktyg – bästa valen", slug: "produktivitetsverktyg", description: "Projekthantering och tidsplanering.", type: "cluster" },
      { title: "Digitalisera ditt företag", slug: "digitalisera-foretag", description: "Checklista för digitalisering.", type: "cluster" },
      { title: "AI för rekrytering och HR", slug: "ai-rekrytering", description: "AI i rekryteringsprocessen.", type: "cluster" },
      { title: "AI och juridik – vad gäller?", slug: "ai-juridik", description: "EU AI Act och GDPR.", type: "cluster" },
    ],
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getAllCategoryArticles(category: Category): Article[] {
  return [...category.pillars, ...category.clusters];
}
